// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthorizeAction = { "Begin": { 
/**
 * Scope of the panel. This is a short identifier to ensure a valid arcadia instance
 */
scope: string, 
/**
 * Redirect URL
 */
redirect_url: string, } } | { "CreateSession": { 
/**
 * Discord OAuth2 code
 */
code: string, 
/**
 * Redirect URL
 */
redirect_url: string, } } | { "CheckMfaState": { 
/**
 * Login Token
 */
login_token: string, } } | { "ResetMfaTotp": { 
/**
 * Login token
 */
login_token: string, 
/**
 * Old MFA code
 */
otp: string, } } | { "ActivateSession": { 
/**
 * Login token
 */
login_token: string, 
/**
 * MFA code
 */
otp: string, } } | { "Logout": { 
/**
 * Login token
 */
login_token: string, } };