// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BaseAnalytics = { bot_counts: { [key: string]: bigint }, server_counts: { [key: string]: bigint }, ticket_counts: { [key: string]: bigint }, total_users: bigint, changelogs_count: bigint, };