// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlogAction = "ListEntries" | { "CreateEntry": { 
/**
 * Slug/vanity code for the blog entry to add
 */
slug: string, 
/**
 * Title of the blog entry to add
 */
title: string, 
/**
 * Description of the blog entry
 */
description: string, 
/**
 * The content of the blog entry
 */
content: string, 
/**
 * The tags for the blog entry
 */
tags: Array<string>, } } | { "UpdateEntry": { 
/**
 * The internal id of the blog post
 */
itag: string, 
/**
 * Slug/vanity code for the blog entry to edit
 */
slug: string, 
/**
 * Title of the blog entry to edit
 */
title: string, 
/**
 * Description of the blog entry
 */
description: string, 
/**
 * The content of the blog entry
 */
content: string, 
/**
 * The tags for the blog entry
 */
tags: Array<string>, 
/**
 * Whether or not the blog entry is a draft or not
 */
draft: boolean, } } | { "DeleteEntry": { 
/**
 * ID of the entry to delete
 */
itag: string, } };