// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlogPost = { 
/**
 * The internal id of the blog post
 */
itag: string, 
/**
 * Slug/vanity code for the blog entry to add
 */
slug: string, 
/**
 * Title of the blog entry to add
 */
title: string, 
/**
 * Description of the blog entry
 */
description: string, 
/**
 * User ID who made the blog entry
 */
user_id: string, 
/**
 * When the blog post was created
 */
created_at: string, 
/**
 * The content of the blog entry
 */
content: string, 
/**
 * Whether or not the blog entry is a draft or not
 */
draft: boolean, 
/**
 * The tags for the blog entry
 */
tags: Array<string>, };