// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BotWhitelist = { 
/**
 * The Bot's ID
 */
bot_id: string, 
/**
 * The user id who added the bot to the whitelist
 */
user_id: string, 
/**
 * The reason
 */
reason: string, 
/**
 * The time the tier was created
 */
created_at: string, };