// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BotWhitelistAction = "List" | { "Add": { 
/**
 * The ID of the bot
 */
bot_id: string, 
/**
 * The reason
 */
reason: string, } } | { "Edit": { 
/**
 * The ID of the bot
 */
bot_id: string, 
/**
 * The reason
 */
reason: string, } } | { "Delete": { 
/**
 * The ID of the bot
 */
bot_id: string, } };