// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Capability = "Rpc" | "ViewBotQueue" | "Search" | "PartnerManagement" | "CdnManagement" | "ChangelogManagement" | "BlogManagement" | "ViewApps" | "ManageApps";