// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CdnAssetAction = "ListPath" | "ReadFile" | "CreateFolder" | { "AddFile": { 
/**
 * Allow overwrite of existing file
 */
overwrite: boolean, 
/**
 * Base 64 encoded file contents uploaded as multiple chunks with an ID associated with each chunk
 *
 * Note that uploading chunks needs `cdn.upload_chunk` permission. As it is not possible to upload without
 * using chunks, disabling `cdn.upload_chunk` will disable uploading files without impacting other operations
 */
chunks: Array<string>, 
/**
 * SHA512 hash of the file
 */
sha512: string, } } | { "CopyFile": { 
/**
 * Allow overwrite of existing file
 */
overwrite: boolean, 
/**
 * Delete the original file
 */
delete_original: boolean, 
/**
 * Path to copy to
 */
copy_to: string, } } | "Delete" | { "PersistGit": { 
/**
 * Commit message
 */
message: string, 
/**
 * Current directory push
 *
 * Using this option will only add and push files in the current directory
 */
current_dir: boolean, } };