// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CdnAssetItem = { 
/**
 * Name of the asset
 */
name: string, 
/**
 * Path of the asset
 */
path: string, 
/**
 * Size of the asset
 */
size: bigint, 
/**
 * Last modified time of the asset as unix epoch
 */
last_modified: bigint, 
/**
 * Whether the asset is a directory
 */
is_dir: boolean, 
/**
 * Permissions of the asset
 */
permissions: number, };