// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CdnScopeData = { 
/**
 * Path in local fs (or remote if support is added)
 */
path: string, 
/**
 * Exposed URL for the CDN
 */
exposed_url: string, };