// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangelogAction = "ListEntries" | { "CreateEntry": { 
/**
 * Version for the changelog entry to add
 */
version: string, 
/**
 * Extra description for the version, if applicable
 */
extra_description: string, 
/**
 * Whether or not this is a prerelease
 */
prerelease: boolean, 
/**
 * Added features for the version
 */
added: Array<string>, 
/**
 * Updated features for the version
 */
updated: Array<string>, 
/**
 * Removed features for the version
 */
removed: Array<string>, } } | { "UpdateEntry": { 
/**
 * Version for the changelog entry to update
 */
version: string, 
/**
 * Extra description for the version, if applicable
 */
extra_description: string, 
/**
 * Github HTML for the version, if applicable
 */
github_html: string | null, 
/**
 * Whether or not this is a prerelease
 */
prerelease: boolean, 
/**
 * Added features for the version
 */
added: Array<string>, 
/**
 * Updated features for the version
 */
updated: Array<string>, 
/**
 * Removed features for the version
 */
removed: Array<string>, 
/**
 * Whether or not to publish the version
 */
published: boolean, } } | { "DeleteEntry": { 
/**
 * Version for the changelog entry to delete
 */
version: string, } };