// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PanelServers } from "./PanelServers";

export type CoreConstants = { 
/**
 * URL to the main site (reed is used here currently)
 */
frontend_url: string, 
/**
 * Infernoplex URL
 */
infernoplex_url: string, 
/**
 * CDN URL
 */
cdn_url: string, 
/**
 * Popplio URL
 */
popplio_url: string, 
/**
 * HTMLSanitize URL
 */
htmlsanitize_url: string, 
/**
 * Servers
 */
servers: PanelServers, };