// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Link } from "./Link";

export type CreatePartner = { id: string, name: string, short: string, bot_id: string | null, links: Array<Link>, type: string, user_id: string, };