// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a user
 */
export type InstanceConfig = { 
/**
 * Description of the instance
 */
description: string, 
/**
 * Any warnings for the instance
 */
warnings: Array<string>, };