// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Primitive link type used throughout the list
 */
export type Link = { name: string, value: string, };