// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MFA Login Secret Data
 */
export type MfaLoginSecret = { secret: string, otp_url: string, qr_code: string, };