// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MfaLoginSecret } from "./MfaLoginSecret";

/**
 * MFA Login Data
 */
export type MfaLogin = { info: MfaLoginSecret | null, };