// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PanelPerms { staff: boolean, admin: boolean, hadmin: boolean, ibldev: boolean, iblhdev: boolean, owner: boolean, }