// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Same as CONFIG.servers but using strings instead of NonZeroU64s
 */
export type PanelServers = { main: string, staff: string, testing: string, };