// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PartialUser { id: string, username: string, display_name: string, bot: boolean, avatar: string, }