// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatePartner } from "./CreatePartner";

export type PartnerAction = "List" | { "Create": { 
/**
 * Create partner data
 */
partner: CreatePartner, } } | { "Update": { 
/**
 * Update partner data
 */
partner: CreatePartner, } } | { "Delete": { 
/**
 * ID for the partner to delete
 */
id: string, } };