// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RPCLogEntry = { 
/**
 * ID of the RPC log entry
 */
id: string, 
/**
 * User ID of the entry
 */
user_id: string, 
/**
 * The method used
 */
method: string, 
/**
 * The state/status of the rpc action
 */
state: string, 
/**
 * The data provided
 */
data: any, 
/**
 * When the entry was created at
 */
created_at: string, };