// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RPCField } from "./RPCField";
import type { TargetType } from "./TargetType";

export type RPCWebAction = { 
/**
 * ID of the RPC action
 */
id: string, 
/**
 * Label of the RPC action
 */
label: string, 
/**
 * Description of the RPC action
 */
description: string, 
/**
 * Fields of the RPC action
 */
fields: Array<RPCField>, 
/**
 * Target types supported by the RPC action
 */
supported_target_types: Array<TargetType>, };