// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShopItemAction = "List" | { "Create": { 
/**
 * The ID of the shop item
 */
id: string, 
/**
 * The friendly name of the shop item
 */
name: string, 
/**
 * The description of the shop item
 */
description: string, 
/**
 * The cents the shop item costs
 */
cents: number, 
/**
 * The target type
 */
target_types: Array<string>, 
/**
 * The benefits of the shop item
 */
benefits: Array<string>, 
/**
 * The number of hours the shop item lasts for
 */
duration: number, } } | { "Edit": { 
/**
 * The ID of the shop item
 */
id: string, 
/**
 * The friendly name of the shop item
 */
name: string, 
/**
 * The description of the shop item
 */
description: string, 
/**
 * The cents the shop item costs
 */
cents: number, 
/**
 * The target type
 */
target_types: Array<string>, 
/**
 * The benefits of the shop item
 */
benefits: Array<string>, 
/**
 * The number of hours the shop item lasts for
 */
duration: number, } } | { "Delete": { 
/**
 * The ID of the shop item
 */
id: string, } };