// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shop items are items that can be purchased by users on the shop
 */
export type ShopItemBenefit = { 
/**
 * The ID of the shop item benefit
 */
id: string, 
/**
 * The friendly name of the shop item benefit
 */
name: string, 
/**
 * The description of the shop item benefit
 */
description: string, 
/**
 * The time the shop item benefit was created
 */
created_at: string, 
/**
 * The time the shop item benefit was last updated
 */
last_updated: string, 
/**
 * The target types the benefit can be applied to
 */
target_types: Array<string>, 
/**
 * Who created the shop item benefit
 */
created_by: string, 
/**
 * Who last updated the shop item benefit
 */
updated_by: string, };