// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Link } from "./Link";

export type StaffPositionAction = "ListPositions" | { "SwapIndex": { 
/**
 * Staff Position A
 */
a: string, 
/**
 * Staff Position B
 */
b: string, } } | { "SetIndex": { 
/**
 * The ID of the position
 */
id: string, 
/**
 * The new index of the position
 */
index: number, } } | { "CreatePosition": { 
/**
 * The name of the position
 */
name: string, 
/**
 * The role id associated with this position on Discord [staff server]
 */
role_id: string, 
/**
 * The corresponding role on discord
 */
corresponding_roles: Array<Link>, 
/**
 * The preset permissions of this position
 */
perms: Array<string>, 
/**
 * The icon of the position
 */
icon: string, 
/**
 * The index of the position, higher means further down on hierarchy
 */
index: number, } } | { "EditPosition": { 
/**
 * The ID of the position
 */
id: string, 
/**
 * The name of the position
 */
name: string, 
/**
 * The role id associated with this position on Discord
 */
role_id: string, 
/**
 * The corresponding role on discord
 */
corresponding_roles: Array<Link>, 
/**
 * The preset permissions of this position
 */
perms: Array<string>, 
/**
 * The icon of the position
 */
icon: string, } } | { "DeletePosition": { 
/**
 * The ID of the position
 */
id: string, } };