// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Link } from "./Link";

export type StaffPosition = { 
/**
 * The ID of the position
 */
id: string, 
/**
 * The name of the position
 */
name: string, 
/**
 * The role id associated with this position on Discord
 */
role_id: string, 
/**
 * The preset permissions of this position
 */
perms: Array<string>, 
/**
 * Corresponding roles of the position
 */
corresponding_roles: Array<Link>, 
/**
 * The icon of the position
 */
icon: string, 
/**
 * The index of the position, higher means further down on hierarchy
 */
index: number, 
/**
 * When the staff position was created/added
 */
created_at: string, };