// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StaffDisciplinaryType = { 
/**
 * The id of the type
 */
id: string, 
/**
 * Name of the action
 */
name: string, 
/**
 * Description of the type
 */
description: string, 
/**
 * Whether or not the type is self-assignable
 */
self_assignable: boolean, 
/**
 * The permission limits of the type
 */
perm_limits: Array<string>, 
/**
 * Whether the perm_limits of the disciplinary are 'additory'
 *
 * E.g. do the perms get combined with the users perms, or do they replace them
 */
additory: boolean, 
/**
 * Whether or not this type needs approval
 */
needs_approval: boolean, 
/**
 * Maximum expiry in seconds of the action/type
 */
max_expiry: number | null, 
/**
 * When the staff disciplinary type was created/added
 */
created_at: string, };