// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StaffMemberAction = "ListMembers" | { "EditMember": { 
/**
 * The user id of the member
 */
user_id: string, 
/**
 * The permission overrides of the staff member
 */
perm_overrides: Array<string>, 
/**
 * Whether or not to autosync the member
 */
no_autosync: boolean, 
/**
 * Whether or not the member is 'known' to be 'unaccounted' for
 */
unaccounted: boolean, } };