// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StaffDisciplinaryTypeAction = "ListDisciplinaryTypes" | { "CreateDisciplinaryType": { 
/**
 * The id of the action
 */
id: string, 
/**
 * Name of the action
 */
name: string, 
/**
 * Description of the action
 */
description: string, 
/**
 * Whether or not the action is self-assignable
 */
self_assignable: boolean, 
/**
 * The permission limits of the action
 */
perm_limits: Array<string>, 
/**
 * Whether the perm_limits of the disciplinary are 'additory'
 *
 * E.g. do the perms get combined with the users perms, or do they replace them
 */
additory: boolean, 
/**
 * Whether or not this type needs approval
 */
needs_approval: boolean, 
/**
 * Maximum expiry in seconds of the action/type
 */
max_expiry: number | null, } } | { "EditDisciplinaryType": { 
/**
 * The id of the action
 */
id: string, 
/**
 * Name of the action
 */
name: string, 
/**
 * Description of the action
 */
description: string, 
/**
 * Whether or not the action is self-assignable
 */
self_assignable: boolean, 
/**
 * The permission limits of the action
 */
perm_limits: Array<string>, 
/**
 * Whether the perm_limits of the disciplinary are 'additory'
 *
 * E.g. do the perms get combined with the users perms, or do they replace them
 */
additory: boolean, 
/**
 * Whether or not this type needs approval
 */
needs_approval: boolean, 
/**
 * Maximum expiry in seconds of the action/type
 */
max_expiry: number | null, } } | { "DeleteDisciplinaryType": { 
/**
 * The id of the action
 */
id: string, } };