// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * StartAuth contains the needed data to begin a login
 */
export type StartAuth = { 
/**
 * The URL to redirect to
 */
login_url: string, 
/**
 * The request scope
 */
scope: string, 
/**
 * Response Scope is just a key to allow for the frontend to verify the backend as compatible
 */
response_scope: string, };