// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Vote credits are tier based through slabs
 * (e.g.)For the following tiers
 *
 * - Tier 1: 100 votes at 0.10 cents
 * - Tier 2: 200 votes at 0.05 cents
 * - Tier 3: 50 votes at 0.025 cents
 *
 * Would mean 625 votes would be split as the following:
 *
 * 100 votes: 0.10 cents [Tier 1]
 * Next 200 votes: 0.05 cents [Tier 2]
 * Next 50 votes: 0.025 cents [Tier 3]
 * Last 275 votes: 0.025 cents [last tier used at end of tiering]
 */
export type VoteCreditTier = { 
/**
 * The ID of the tier
 */
id: string, 
/**
 * The target type of the tier
 */
target_type: string, 
/**
 * The position of the tier
 */
position: number, 
/**
 * The cents per vote
 */
cents: number, 
/**
 * The number of votes in this tier
 */
votes: number, 
/**
 * The time the tier was created
 */
created_at: string, };