// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RPCMethod } from "./RPCMethod";
import type { RPCPerms } from "./RPCPerms";
import type { WebField } from "./RPCWebField";

export interface WebAction { id: string, label: string, description: string, needed_perms: RPCPerms, method_example: RPCMethod, fields: Array<WebField>, }