// Code generated by tygo. DO NOT EDIT.

//////////
// source: dovewing.go

export interface State {
  Discord?: any /* discordgo.Session */;
  Logger?: any /* zap.SugaredLogger */;
  PreferredGuild: string;
  Context: any /* context.Context */;
  Pool?: any /* pgxpool.Pool */;
  Redis?: any /* redis.Client */;
  UpdateCache: any;
}
export interface DiscordUser {
  id: string;
  username: string;
  discriminator: string;
  avatar: string;
  bot: boolean;
  status: string /* discord status */;
  nickname: string;
  in_guild: string;
}
