// Code generated by tygo. DO NOT EDIT.

//////////
// source: perms.go

export type TeamPermission = string; // TeamPermission is a permission that a team can have
export const TeamPermissionUndefined: TeamPermission = "";
/**
 * Bot permissions
 */
export const TeamPermissionEditBotSettings: TeamPermission = "EDIT_BOT_SETTINGS";
export const TeamPermissionAddNewBots: TeamPermission = "ADD_NEW_BOTS";
export const TeamPermissionResubmitBots: TeamPermission = "RESUBMIT_BOTS";
export const TeamPermissionCertifyBots: TeamPermission = "CERTIFY_BOTS";
export const TeamPermissionResetBotTokens: TeamPermission = "RESET_BOT_TOKEN";
export const TeamPermissionEditBotWebhooks: TeamPermission = "EDIT_BOT_WEBHOOKS";
export const TeamPermissionTestBotWebhooks: TeamPermission = "TEST_BOT_WEBHOOKS";
export const TeamPermissionGetBotWebhookLogs: TeamPermission = "GET_BOT_WEBHOOK_LOGS";
export const TeamPermissionRetryBotWebhookLogs: TeamPermission = "RETRY_BOT_WEBHOOK_LOGS";
export const TeamPermissionDeleteBotWebhookLogs: TeamPermission = "DELETE_BOT_WEBHOOK_LOGS";
export const TeamPermissionSetBotVanity: TeamPermission = "SET_BOT_VANITY";
export const TeamPermissionDeleteBots: TeamPermission = "DELETE_BOTS";
/**
 * Server permissions
 */
export const TeamPermissionEditServerSettings: TeamPermission = "EDIT_SERVER_SETTINGS";
export const TeamPermissionAddNewServers: TeamPermission = "ADD_NEW_SERVERS";
export const TeamPermissionCertifyServers: TeamPermission = "CERTIFY_SERVERS";
export const TeamPermissionResetServerTokens: TeamPermission = "RESET_SERVER_TOKEN";
export const TeamPermissionEditServerWebhooks: TeamPermission = "EDIT_SERVER_WEBHOOKS";
export const TeamPermissionTestServerWebhooks: TeamPermission = "TEST_SERVER_WEBHOOKS";
export const TeamPermissionGetServerWebhookLogs: TeamPermission = "GET_SERVER_WEBHOOK_LOGS";
export const TeamPermissionRetryServerWebhookLogs: TeamPermission = "RETRY_SERVER_WEBHOOK_LOGS";
export const TeamPermissionDeleteServerWebhookLogs: TeamPermission = "DELETE_SERVER_WEBHOOK_LOGS";
export const TeamPermissionSetServerVanity: TeamPermission = "SET_SERVER_VANITY";
export const TeamPermissionDeleteServers: TeamPermission = "DELETE_SERVERS";
/**
 * Common permissions
 */
export const TeamPermissionEditTeamInfo: TeamPermission = "EDIT_TEAM_INFO";
export const TeamPermissionAddTeamMembers: TeamPermission = "ADD_TEAM_MEMBERS";
export const TeamPermissionRemoveTeamMembers: TeamPermission = "REMOVE_TEAM_MEMBERS";
export const TeamPermissionEditTeamMemberPermissions: TeamPermission = "EDIT_TEAM_MEMBER_PERMISSIONS";
/**
 * Owner permission
 */
export const TeamPermissionOwner: TeamPermission = "OWNER";
export interface PermDetailMap {
  id: TeamPermission;
  name: string;
  desc: string;
  group: string;
}
/**
 * PermissionManager is a manager for team permissions
 */
export interface PermissionManager {
}
