// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnboardingMeta } from "./OnboardingMeta";
import type { Question } from "./Question";

export interface OnboardResponse { user_id: string, questions: Array<Question>, answer: Record<string, string>, data: Record<string, string>, meta: OnboardingMeta, }