// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Question } from "./Question";
import type { Verdict } from "./Verdict";

export interface OnboardResponse { user_id: string, questions: Array<Question> | null, answers: Record<string, string> | null, verdict: Verdict | null, created_at: bigint, finished_at: bigint | null, }